### ISSUE TITLE
No provider records, no peers

### ISSUE THREAD

**Issue by dokterbob** [libp2p/hydra-booster#110]
I've been running 0.4.3 for about a week on a Gigabit machine with public IP (AND an IPFS node running). Somehow, I only seem to get about 5 peers and no provider records whatsoever.

I am currently running 0.5 for some time and am observing the same behaviour.

Is there perhaps something I've missed, or a default configuration option that does not make sense?

We'd like to run a booster to harvest more hashes to index for ipfs-search.com and this is currently blocking further [development on our side](https://github.com/ipfs-search/hydra-booster/tree/provider_stream).

Example output (it starts with 7 peers):
```
Hydra Booster

Head ID(s)               [<...>]
Connections              1 peers
Unique Peers Seen        7
Memory Allocated         28 MB
Stored Provider Records  0
Routing Table Size       0
Uptime                   0h 35m 37s
```

Thanks!

**Comment by alanshaw** [comment]
What configuration flags are you using? Looks like the hydra heads are not publically accessible.

**Comment by dokterbob** [comment]
First, I started it with default options. The host is running on a public IP, there's no firewall and I have confirmed that I can make a TCP connection to listening ports.

In addition, I've tried starting it with two IPFS nodes I control as bootstrap peers (running 0.4.23 and 0.5.1), with similar results (2 peers connected, few unique peers seen and no provider records).

I've just ran another test on 0.6.0, again with similar results.

In all cases I compiled without OpenSSL as I'm doing a cross-compile from Mac to Linux. Example output for 0.6.0:
```
[NumHeads: 1, Uptime: 10m50s, MemoryUsage: 38 MB, PeersConnected: 1, TotalUniquePeersSeen: 8, BootstrapsDone: 1, ProviderRecords: 0, RoutingTableSize: 0]
```

**Comment by alanshaw** [comment]
hmm, what does the /heads HTTP API say?

**Comment by alanshaw** [comment]
Ah, try setting the HYDRA_ENABLE_V1_COMPAT env var to true.

**Comment by dokterbob** [comment]
K'bam!

```
env HYDRA_ENABLE_V1_COMPAT=true ./hydra-booster -metrics-addr 127.0.0.1:8888
hydra-booster
🐉 Hydra Booster starting up...
📊 Prometheus metrics and pprof server listening on http://127.0.0.1:8888
🥞 Using LevelDB datastore
💭 Using in-memory peerstore
🐲 Spawning 1 heads: .
🆔[...]
🐝 Swarm listening on /ip4/[...]/tcp/37159
🐝 Swarm listening on /ip4/127.0.0.1/tcp/37159
🐝 Swarm listening on /ip4/[...]//udp/41548/quic
🐝 Swarm listening on /ip4/127.0.0.1/udp/41548/quic
🧩 HTTP API listening on http://127.0.0.1:7779
[NumHeads: 1, Uptime: 0s, MemoryUsage: 19 MB, PeersConnected: 0, TotalUniquePeersSeen: 0, BootstrapsDone: 0, ProviderRecords: 0, RoutingTableSize: 0]
[NumHeads: 1, Uptime: 5s, MemoryUsage: 28 MB, PeersConnected: 37, TotalUniquePeersSeen: 37, BootstrapsDone: 1, ProviderRecords: 0, RoutingTableSize: 35]
[NumHeads: 1, Uptime: 10s, MemoryUsage: 35 MB, PeersConnected: 51, TotalUniquePeersSeen: 51, BootstrapsDone: 1, ProviderRecords: 0, RoutingTableSize: 50]
[NumHeads: 1, Uptime: 15s, MemoryUsage: 39 MB, PeersConnected: 59, TotalUniquePeersSeen: 59, BootstrapsDone: 1, ProviderRecords: 0, RoutingTableSize: 55]
[...]
```
