### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by alanshaw** [libp2p/hydra-booster#13]
There's no tests 😱

- [x] SpawnNode (@alanshaw)
- [ ] RunMany (@alanshaw)
- [ ] RunSingle (@alanshaw)
- [x] Add Code Coverage to CI (@alanshaw)
- [x] Then update the deps and see what breaks :)

**Comment by daviddias** [comment]
@alanshaw seems that you are owning all of these. Will tag the issue to you. Thank you btw :)
