### ISSUE TITLE
Fix count(*) queries

### ISSUE THREAD

**Issue by BigLep** [libp2p/hydra-booster#147]
# Backround
From @aschmahmann over slack: 

> I'm a bit concerned about the hydras and/or the metrics reporting. I'm seeing that the number of provider records we're storing has been fairly stable at around 1.5B for a while.
> 
> While that doesn't have to necessarily be a big cause for concern, IIUC the .storage nodes are accumulating more data to store which means we should reasonably be accumulating more records unless there's a problem on our end or theirs.
> 
> Can we make sure that the database is doing ok and perhaps do a slower, more accurate, DB size check?
> 
> Note: I'm not totally sure off hand, but there's also the possibility that if we're too slow to at adding data that users of the accelerated client could just move on and store the data on non-hydra nodes which would lead to the network still working fine, but the hydra nodes becoming a bit of a network hinderance and also not reporting the metrics we want.

# Impact
1. Not getting accurate DHT count in our metrics
2. DHT performance could see some degradation if the Hydra's aren't holding the latest records.  

# Actions
As part of the slack thread, we identified that the disk utilization is 97+%.  The immediate action is to increase the disk size.

**Comment by BigLep** [comment]
Correspondence in Slack:

aschmahmann Jan 4th at 20:28
@Petar Maymounkov @thattommyhall I'm a bit concerned about the hydras and/or the metrics reporting. I'm seeing that the number of provider records we're storing has been fairly stable at around 1.5B for a while.
While that doesn't have to necessarily be a big cause for concern, IIUC the .storage nodes are accumulating more data to store which means we should reasonably be accumulating more records unless there's a problem on our end or theirs.
Can we make sure that the database is doing ok and perhaps do a slower, more accurate, DB size check?
Note: I'm not totally sure off hand, but there's also the possibility that if we're too slow to at adding data that users of the accelerated client could just move on and store the data on non-hydra nodes which would lead to the network still working fine, but the hydra nodes becoming a bit of a network hinderance and also not reporting the metrics we want.
30 replies

Petar Maymounkov  1 day ago
@thattommyhall ssh hydratest gives me permission denied. has anything changed there?

thattommyhall  1 day ago
Hey hey, i killed it as it was running an older version

thattommyhall  1 day ago
Yinnis spotted it in some monitoring he was doing

thattommyhall  1 day ago
Now you have access to DO you can whitelist your IP in the DB (or send me it)

Petar Maymounkov  1 day ago
My home machine probably doesn’t have a stable IP. I could log into alasybil, install postgres and contact the db from there. One option.

thattommyhall  1 day ago
yeah, thats not terrible, not A tho as shes special as shes responsible for the counts and stuff

thattommyhall  1 day ago
it deffo works, I did it to troubleshoot issues with the DB connection at one point

Petar Maymounkov  1 day ago
select count(*) from records; is hanging for me. calling it from jetta-

thattommyhall  1 day ago
\d records does return tho?

Petar Maymounkov  1 day ago
Right. So it looks like, count(*) is not working, and approximate counting is still available `SELECT reltuples AS estimate FROM pg_class where relname = ‘records’;
  estimate
-------------
 1.48874e+09
(1 row)`

Petar Maymounkov  1 day ago
i suspect that count(*) has not been operational since the incident we had. it’s a possible since we switched to approximate counting in the code.

thattommyhall  1 day ago
disk is near 100, I can scale up again unless there is a way to prune them? (edited) 

thattommyhall  1 day ago
DO only saves 2 weeks and its been at that the whole time (edited) 

Petar Maymounkov  1 day ago
I don’t see a pruning operation in postgres. Let’s just check that 100% disk equates roughly to the 1.5B records we have, at least ballpark

Petar Maymounkov  1 day ago
How much is the disk space exactly?

Petar Maymounkov  1 day ago
disk_space / 1.5B = should produce something comparable to size of one record (off by at most say 3x)

thattommyhall  1 day ago
between 94 and 97%

thattommyhall  1 day ago
64 GB RAM / 16vCPU / 1012 GB Disk

thattommyhall  1 day ago
looks like I can hlaf the CPU and near double the disk for the same price

thattommyhall  1 day ago
Screenshot-20220105184519-1543x401.png 
Screenshot-20220105184519-1543x401.png



thattommyhall  1 day ago
feels like a no-brainer to me

thattommyhall  1 day ago
we :thumbsup:
:+1:
1


Petar Maymounkov  1 day ago
sounds reasonable to me. the disk has about 660bytes per record, which seems reasonable

thattommyhall  1 day ago
one thing is tho, I think we failed when the disk was full in the past, why would it just stop there and not obviously fail?

thattommyhall  1 day ago
dang, not available in this region

Petar Maymounkov  1 day ago
right … that may not be the root cause. probably won’t fix ‘count(*)’. maybe lets try count(*) after the upgrade …

thattommyhall  24 hours ago
Nowhere to go quickly infra-wise. Are we sure that at the db entries are cleaned up when they time out etc? They are all legit?

thattommyhall  24 hours ago
I can try asking them for the bigger machine type

aschmahmann  24 hours ago
Are we sure that at the db entries are cleaned up when they time out etc?
Note: I am sure that the IPNS records are not cleaned up, however my understanding is that we don't have a ton of those. I could be wrong though.

**Comment by BigLep** [comment]
@thattommyhall : regardless of cost, can we just move to a larger instance?  (I recognize that vertically scaling won't save us forever, but at least want to unblock for now until we get ownership for this code and infra determined: https://github.com/libp2p/hydra-booster/issues/148 )

@petar : to be clear, the graphs we look for DHT size don't just use approximate counts, is that right, they use full count(*) counts?

**Comment by thattommyhall** [comment]
None available in the region im afraid, nowhere to go w/o raising an issue with DO

**Comment by petar** [comment]
> @petar : to be clear, the graphs we look for DHT size don't just use approximate counts, is that right, they use full count(*) counts?
The graphs which I think @aschmahmann is looking at are on grafana. They are updated by the hydras themselves, using an approximate count query.

@aschmahmann points out that the approximate counts have stayed oddly flat for awhile (as reported in grafana).

As a result, we log directly into the database to attempt an exact count query. 
We discover that exact counting hangs. While the rest of the postgres functionality seems operational.

**Comment by BigLep** [comment]
Dashboard we're looking at: https://protocollabs.grafana.net/d/lNGQTv9Zz/hydra-boosters?orgId=1&refresh=1d&from=now-90d&to=now

2022-01-07 discussion:

Things we need:
1. Graphs on disk utilization
2. Find out what region/instance we're using in DO
3. What would it take to spin up a new instance that is larger, even if it's in a new region?
4. Are we sure disks are filled up by the DB?
5. Chief concern is if the Hydras start stalling/blackholing requests.  Are there metrics or logs that show whether this is happening or not?
6. Need to get accelerated DHT client to be non experimental (e.g., add the tests so we feel confident about its performance in different problems).
7. What is the geographic architecture for the Hydras.  Where are the hydra nodes vs. the DB instances.

How does Hydras blackholing request affect the accelerated DHT client (which is used by the gateways)
* On startup, scans the whole network.  Worst case would be Hydra nodes blackhole/stall when gateway tries to connect to Hydra peers, slowing down startup.
 - We can filter by addresses to not talk to Hydras if necessary.

There's a lot of questions here.  My hope is we can find a way to get this to vertically scale as quickly as possible and then give us some runway to figure this all out.

**Comment by thattommyhall** [comment]
I've started building a new cluster in `sfo3`, will use a different seed for it and a new empty DB at first, we can sync DB and set the seed to the same as current if we want to keep the IDs

**Comment by BigLep** [comment]
@thattommyhall : thanks!

For reference: internal PL slack thread: https://protocollabs.slack.com/archives/C9A8NQQ6S/p1641579724025900

**Comment by BigLep** [comment]
Per internal PL slack discussion, PL's instance is going to move to an in-progress DDB peerstore.  This is the issue for that work: https://github.com/protocol/hydra-booster-k8s/issues/2

**Comment by BigLep** [comment]
See also https://github.com/libp2p/hydra-booster/issues/153

**Comment by BigLep** [comment]
This was handled by https://github.com/libp2p/hydra-booster/issues/153 .  Resolving.
