### ISSUE TITLE
Stage 2 - Hydra Heads with Pre-Calculated Peer IDs 

### ISSUE THREAD

**Issue by alanshaw** [libp2p/hydra-booster#18]
> Effort Needed: Low (1 week of developing + testing + deployment)
> Prerequisite(s): None, can be shipped in a go-ipfs 0.4.X (Yes, stage 2 can be done in parallel)

## Design notes & tasks
* Calculate the number of heads (PeerIds) necessary for networks of multiple sizes (10K, 100K, 1000K)
* Brute force to calculate an even distribution of those PeerIds
* Use those selected ids as PeerIds for the Hydra Booster sybils

## Testing mechanics & evaluation plan
* We run the DHT scrapper daily and visualize the PeerIds distribution and where the hydra PeerIds show
* We simulate generating the routing tables for such nodes and verify if indeed the hydra nodes are 1~3 hops away from each other node.

## Success criteria
Our Hydra nodes ate 1~3 hops away from every other node in the Network

**Comment by daviddias** [comment]
We ended up using "Power of 2 choices" for this rather than pre-calculating.

**Comment by thattommyhall** [comment]
I power of 2 along with the recent deterministic peerids addresses the intent of this issue
