### ISSUE TITLE
List listening multiaddrs on ui

### ISSUE THREAD

**Issue by daviddias** [libp2p/hydra-booster#32]
It would be cool to have a "listening multiaddrs" so that we can quickly connect to it if needed.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1211152/76400550-6af6b580-6378-11ea-882a-c6ef70952b2b.png">

**Comment by alanshaw** [comment]
We could have the UI call the HTTP API (`/sybils`) to get this info.
