### ISSUE TITLE
Build a tool to help us understand the DHT (Visually is a ++)

### ISSUE THREAD

**Issue by daviddias** [libp2p/hydra-booster#40]
With the this tool, we should be able to answer:
- Where are the sybils in comparison to other nodes
- Are 1~3 hops away from each other non sybil node? (Simulating ideal routing tables)
- How many more sybils would we need to generate to make the above happen

**Comment by alanshaw** [comment]
This might be a series of visualisations.

I had one idea, not sure if it's achivable - I'd love to see a heat map for peers in the DHT identifying where we've placed hydra sybils. Not only would this validate that we're putting them in the right places, but it might show us hot spots where we should be putting additional sybils. Before that though it would answer the question of whether there even are hot spots 🤔.

<img width="192" alt="Screenshot 2020-03-19 at 19 38 12" src="https://user-images.githubusercontent.com/152863/77109383-b580cd80-6a1b-11ea-9f29-a258717b409c.png">

**Comment by alanshaw** [comment]
Lets track this over here https://github.com/libp2p/hydra-booster/issues/68
