### ISSUE TITLE
Multiple GC runs for provider records

### ISSUE THREAD

**Issue by alanshaw** [libp2p/hydra-booster#74]
We share a datastore but every sybil will be running GC on the provider records in the store. So for 200 sybils we get 200 GC runs periodically that we could avoid 199 of.

If we could pass a garbage collector to the DHT or signal to the DHT to not GC somehow we could just do one sweep.

cc @daviddias @aschmahmann @willscott @Stebalien

**Comment by willscott** [comment]
there should be enough of a hook to do this already:
* the IpfsDHT.ProviderManager is a public field, you can take one instance of the created provider manager, and set it as a shared manager for all of the hydra heads.
* before replacing the other managers that have been created, you can spin them down with `IpfsDHT.ProviderManager.Process().Close()`

One thing we may want to expose is provide a way to let this single provider manager instance have a larger cache size than normal.

**Comment by Stebalien** [comment]
I'd actually just add an option to pass a pre-constructed provider manager into the DHT (as long as we keep the interface sufficiently minimal).

**Comment by alanshaw** [comment]
Thinking about it, I'd rather _not_ do this, since the provider manager is not an insignificant piece of code and keeping our own modified package in sync with improvements made to the package in go-libp2p-kad-dht will be a maintenance overhead. I was thinking something along the lines of an option to set the GC period really really high (to effectively disable it), so no actual complicated code changes happen.

That said, I need to figure out what to do about the LRU cache (which gets wiped on GC) in the case when GC is disabled. This might call for a bigger change than the above proposal.

**Comment by Stebalien** [comment]
You shouldn't need to fork anything. We can change the DHT such that it accepts a new `ProviderManager` option. If unspecified, the DHT will construct its own provider manager. Hydra could construct a shared provider manager and pass the same one to all instances.

**Comment by alanshaw** [comment]
https://github.com/libp2p/go-libp2p-kad-dht/pull/591

**Comment by alanshaw** [comment]
re-thought as https://github.com/libp2p/go-libp2p-kad-dht/pull/593
